#   **46.6 async/await**


-   비동기 처리를 동기 처리처럼 동작하도록 구현할 수 있다

-   **프로미스를 기반으로 동작**

-   async/await을 사용하면 프로미스의 후속 처리 메서드 없이 마치 **동기 처리처럼 프로미스를 사용할 수 있다**

##   46.6.1 async 함수

-   정의 방법 : `async` 키워드를 사용
    
-   반환값 : 언제나 프로미스
    
    async 함수가 명시적으로 프로미스를 반환하지 않더라도, async 함수는 암묵적으로 반환값을 `resolve`하는 프로미스를 반환
    
-   클래스의 constructor 메서드는 async 메서드가 될 수 없다.
    
    ```jsx
    class MyClass {
      async constructor() { }
      // SyntaxError: Class constructor may not be an async method
    }
    
    const myClass = new MyClass();
    ```
    
    클래스의 constructor는 인스턴스를 반환해야 하지만 async 함수는 언제나 프로미스를 반환해야 한다.
    
    _좀 이해가 안됨.. 설명이 더 필요해_
    
##   46.6.2 await 키워드

-   **반드시 `async` 함수 내부에서 사용해야 한다.**
-   **반드시 프로미스 앞에서 사용해야 한다.**
-   프로미스가 settled 상태가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 **resolve한 처리 결과를 반환**
-   **다음 실행을 일시 중지시켰다가 프로미스가 settled 상태가 되면 재개**

-   ⚠️ 모든 프로미스에 await 키워드를 사용하는 것은 주의해야 한다 ⚠️
    
    ```jsx
    async function foo() {
      const a = await new Promise(resolve => setTimeout(() => resolve(1), 3000));
      const b = await new Promise(resolve => setTimeout(() => resolve(2), 2000));
      const c = await new Promise(resolve => setTimeout(() => resolve(3), 1000));
    
      console.log([a, b, c]); // [1, 2, 3]
    }
    
    foo();
    ```
    
    위 예제의 foo는 종료할때까지 약 6초가 걸린다. 
    
    그런데 foo가 수행하는 3개의 비동기 처리는 서로 연관이 없이 개별적으로 수행되는 비동기 처리이므로 → 앞선 비동기 처리가 완료될때까지 대기해서 순차적으로 처리할 필요가 없다. 따라서 → foo는 아래와 같이 처리하는 것이 좋다
    
    ```jsx
    async function foo() {
      const res = await Promise.all([
        new Promise(resolve => setTimeout(() => resolve(1), 3000)),
        new Promise(resolve => setTimeout(() => resolve(2), 2000)),
        new Promise(resolve => setTimeout(() => resolve(3), 1000))
      ]);
    
      console.log(res); // [1, 2, 3]
    }
    
    foo(); // 약 3초 소요된다.
    ```


##   46.6.3 에러 처리


비동기 처리를 위한 콜백 패턴의 단점 중 가장 심각한 것은 에러 처리가 곤란하다는 것

에러는 호출자 방향으로 전파된다. 비동기 함수의 콜백 함수를 호출한 것은 비동기 함수가 아니기 때문에 try … catch문을 사용해 에러를 캐치할 수 없다.

**async/await에서 에러 처리는 try … catch 문을 사용**할 수 있다. (콜백 함수를 인수로 전달받는 비동기 함수와는 달리) 프로미스를 반환하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 호출자가 명확하다.

```jsx
const fetch = require('node-fetch');

const foo = async () => {
  try {
    const wrongUrl = '<https://wrong.url>';

    const response = await fetch(wrongUrl);
    const data = await response.json();
    console.log(data);
  } catch (err) {
    console.error(err); // TypeError: Failed to fetch
  }
};

foo();
```
    
-   `async` 함수 내에서 `catch` 문을 사용해서 에러 처리를 하지 않으면
    
    `async` 함수는 발생한 에러를 `reject`하는 프로미스를 반환한다. 따라서 → `async` 함수를 호출하고 `Promise.prototype.catch` 후속 처리 메서드를 사용해 에러를 캐치할 수도 있다.
    
    ```jsx
    const foo = async () => {
      const wrongUrl = '<https://wrong.url>';
    
      const response = await fetch(wrongUrl);
      const data = await response.json();
      return data;
    };
    
    foo()
      .then(console.log)
      .catch(console.error); // TypeError: Failed to fetch
    ```
